# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 063f796c3113e0d6a84a915f2d09a94ac5def90afe159341afebe15c9db93ad8ed2240dbaa776228cca1d186fdaa0ef01a5e714c928674b50103e34489d71dfc

test:
  secret_key_base: d128e3db987483c08792f24296e82eb163a0801a226ad4a5a23170b8b6687220207dbcbf280ca7fefad82cdd24b4b0139ae2f1fd7f90181aa3b030fe222a193c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
